"""create shots model

Revision ID: ec6d53bb35b5
Revises: fb7ce39dbe8d
Create Date: 2025-05-07 00:28:39.215281

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec6d53bb35b5"
down_revision: Union[str, None] = "fb7ce39dbe8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shot_log",
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("shot_time", sa.Time(), nullable=False),
        sa.Column("shot_date", sa.Date(), nullable=False),
        sa.Column("primary_score", sa.Float(), nullable=False),
        sa.Column("match_shot", sa.Integer(), nullable=False),
        sa.Column("firing_point", sa.Integer(), nullable=False),
        sa.Column("secondary_score", sa.Float(), nullable=False),
        sa.Column("divisions", sa.Integer(), nullable=False),
        sa.Column("inner_ten", sa.Boolean(), nullable=False),
        sa.Column("x_mm", sa.Float(), nullable=False),
        sa.Column("y_mm", sa.Float(), nullable=False),
        sa.Column("in_time", sa.Boolean(), nullable=False),
        sa.Column("time_since_change", sa.Float(), nullable=False),
        sa.Column("sweep_direction", sa.Integer(), nullable=False),
        sa.Column("demonstration", sa.Boolean(), nullable=False),
        sa.Column("shoot_index", sa.Integer(), nullable=False),
        sa.Column("practice_index", sa.Integer(), nullable=False),
        sa.Column("insdel", sa.Integer(), nullable=False),
        sa.Column("total_kind", sa.Integer(), nullable=False),
        sa.Column("group_enum", sa.Integer(), nullable=False),
        sa.Column("fire_kind", sa.Integer(), nullable=False),
        sa.Column("log_event", sa.Integer(), nullable=False),
        sa.Column("log_type", sa.Integer(), nullable=False),
        sa.Column("time_of_year", sa.Float(), nullable=False),
        sa.Column("relay_number", sa.Integer(), nullable=False),
        sa.Column("weapon_type", sa.Integer(), nullable=False),
        sa.Column("shooting_position", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("external_number", sa.Integer(), nullable=True),
        sa.Column("import_date", sa.Date(), nullable=False),
        # sa.ForeignKeyConstraint(
        #     ["athlete_id"],
        #     ["athletes.id"],
        # ),
        # Remove the foreign key constraint since athletes might not be registered
        sa.PrimaryKeyConstraint("athlete_id", "shot_time", "shot_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shot_log")
    # ### end Alembic commands ###
